use_frameworks!

platform :ios, '10.0'

target 'swc-utils_Example' do
  pod 'swc-utils', :path => '../'

  target 'swc-utils_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
