# This is a workflow that syncs everthing on this repository to another repository
 
name: swc/mobile/swift/swc-utils
 
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
jobs:
  push-to-gitlab:
    runs-on: ubuntu-latest
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches
      - name: Set remote repository
        env:
	  gitlab_url: ${GITLAB_URL}
          gitlab_username: ${GITLAB_USERNAME}
          gitlab_token: ${GITLAB_TOKEN}
        run: |
	  echo "target url : ${gitlab_url}"
          git remote add gitlab https://${gitlab_username}:${gitlab_token}@${gitlab_url#https://};
      - name: Force push everthing
        run: | i
          git push -f --all gitlab;
          git push -f --tags gitlab;
